AWSTemplateFormatVersion: "2010-09-09"
Description: A template for implementing EC2 schedule
Resources:
  LambdaExecutionRole: #Role for Lambda
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
  LambdaPolicy:
    DependsOn:
      - "LambdaExecutionRole"
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: LambdaSchedulePolicy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        -
          Effect: Allow
          Action:
          - logs:*
          Resource: arn:aws:logs:*:*:*
        -
          Effect: Allow
          Action:
          - ec2:DescribeInstances
          - ec2:StartInstances
          - ec2:StopInstances
          Resource: "*"
        -
          Effect: Allow
          Action:
          - s3:*
          Resource: arn:aws:s3:::*
      Roles:
        -
          Ref: "LambdaExecutionRole"

  LambdaSchedule: #Main function
    Type: "AWS::Lambda::Function"
    Properties:
      Handler: "code.lambda_handler"
      Role:
        Fn::GetAtt:
        - "LambdaExecutionRole"
        - "Arn"
      Code:
        S3Bucket: "aferno-schedule"
        S3Key: "code.zip"
      Runtime: "python2.7"
      Timeout: "60"
  ScheduledRule: #Schedule
    Type: "AWS::Events::Rule"
    Properties:
      Description: "ScheduledRule"
      ScheduleExpression: "cron(54 21 ? * SUN-SAT *)"
      State: "ENABLED"
      Targets:
        -
          Arn:
            Fn::GetAtt:
              - "LambdaSchedule"
              - "Arn"
          Id: "TargetFunctionV1"
  PermissionForEventsToInvokeLambda: #Permission
    Type: "AWS::Lambda::Permission"
    Properties:
      FunctionName:
          Ref: "LambdaSchedule"
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn:
        Fn::GetAtt:
          - "ScheduledRule"
          - "Arn"
