AWSTemplateFormatVersion: "2010-09-09"
Description: A template for implementing EC2 schedule
Resources:
  LambdaExecutionRole: #Role for Lambda
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
  LambdaPolicy:
    DependsOn:
      - "LambdaExecutionRole"
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: LambdaSchedulePolicy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        -
          Effect: Allow
          Action:
          - logs:*
          Resource: arn:aws:logs:*:*:*
        -
          Effect: Allow
          Action:
          - ec2:DescribeInstances
          - ec2:StartInstances
          - ec2:StopInstances
          Resource: "*"
        -
          Effect: Allow
          Action:
          - dynamodb:*
          Resource: arn:aws:dynamodb:*:*:*
      Roles:
        -
          Ref: "LambdaExecutionRole"

  LambdaSchedule: #Main function
    Type: "AWS::Lambda::Function"
    Properties:
      Handler: "code.lambda_handler"
      Role:
        Fn::GetAtt:
        - "LambdaExecutionRole"
        - "Arn"
      Code:
        S3Bucket: "aferno-schedule"
        S3Key: "code.zip"
      Runtime: "python2.7"
      Timeout: "60"
Outputs:
  LambdaSchedule:
    Value:
      Fn::GetAtt:
      - "LambdaSchedule"
      - "Arn"
